### ISSUE TITLE
Code completion not working with Go 1.9 RC 2.

### ISSUE THREAD

**Issue by shurcooL** [DisposaBoy/GoSublime#775]
It appears that code completion isn't working when using GoSublime with Go 1.9 RC 2.

Specifically, it works on identifiers of package you're working on, but not on other packages you've imported. I suspect it's because the bundled `gocode` (MarGo?) version is not compatible with .a files of Go 1.9 RC 2 (but this is a guess and I could be wrong).

![image](https://user-images.githubusercontent.com/1924134/29597544-426e1c04-8791-11e7-96f9-6ee925e21931.png)

![image](https://user-images.githubusercontent.com/1924134/29597561-551b6208-8791-11e7-9444-f00918f43382.png)

![image](https://user-images.githubusercontent.com/1924134/29597553-4f85a830-8791-11e7-8ca8-2ff18d6347c1.png)

I've done `go install -v github.com/google/go-github/github` and the package is installed. `fmt` is also installed, since it's a part of a normal Go installation.

Using macOS, Sublime Text (3), GoSublime, Go 1.9 RC 2. Latest (stable) versions of everything:

- macOS Sierra 10.12.6
- Sublime Text (3), Dev Channel, Build 3142
- `go version go1.9rc2 darwin/amd64`
- latest version of GoSublime via Package Control (I'm not sure if installing from there is supported anymore, or am I supposed to install GoSublime directly by git cloning its repository into Sublime Text?)

![image](https://user-images.githubusercontent.com/1924134/29597600-a8b5b63e-8791-11e7-998c-c356677b9bbb.png)

I've tried downgrading to Go 1.8.3 and that resolves the issue:

![image](https://user-images.githubusercontent.com/1924134/29597689-46ee9208-8792-11e7-9934-0f3327c03e2e.png)

Reinstalling Go 1.9 afterwards makes it no longer work, once again. So it's quite clear this issue is caused by Go 1.9.

/cc @mholt Was also having trouble with this, also on Go 1.9.

**Comment by shurcooL** [comment]
The version of GoSublime I have via Package Control is:

![image](https://user-images.githubusercontent.com/1924134/29597885-9349b924-8793-11e7-858c-8fa621627000.png)

I can't tell if that's the latest or not.

According to https://github.com/DisposaBoy/GoSublime#installation, I don't see Package Control listed as a supported installation source, so perhaps that's the problem. (I vaguely recall support for it being removed, but I can't quite recall if it was this project or another...)

I think the next step to investigate this issue is to try installing GoSublime via `git clone` as described in https://github.com/DisposaBoy/GoSublime#installation and see if that fixes this issue or not.

**Comment by DisposaBoy** [comment]
I updated gocode which should fix it, but I didn't test it cos I haven't used this released version of GoSublime for years.

I dropped support for Package Control a while ago https://github.com/DisposaBoy/GoSublime/blob/master/SUPPORT.md

**Comment by mholt** [comment]
So, just to clarify - we are not supposed to install this with Package Control? (Later in that doc it suggests turning off auto-updates, which seems counter-intuitive to using Package Control at all.)

I will uninstall with Package Control and git clone manually if that is recommended.

**Comment by shurcooL** [comment]
@DisposaBoy, I see you've made a new release 7 hours ago:

https://github.com/DisposaBoy/GoSublime/releases/tag/r17.08.23-1

It showed up as an available update in Package Control, and after updating to it and restarting ST, code completion works well for me with Go 1.9 RC 2:

![image](https://user-images.githubusercontent.com/1924134/29643392-d75284ee-883c-11e7-9ce2-9ca0ff2329b7.png)

![image](https://user-images.githubusercontent.com/1924134/29643399-e06e59f4-883c-11e7-920a-1bda4a1a8c06.png)

So I think this issue is resolved. Thank you for a prompt response.

> I dropped support for Package Control a while ago https://github.com/DisposaBoy/GoSublime/blob/master/SUPPORT.md

Thanks for pointing that out. I understand that installing GoSublime via Package Control is not supported by you, so next time I have an issue with GoSublime, I will follow the installation steps as described at https://github.com/DisposaBoy/GoSublime#installation before reporting an issue.

**Comment by mholt** [comment]
Yay it works! Thanks from me as well for the quick update, and for clarifying that package control isn't updated.

**Comment by DisposaBoy** [comment]
GoSublime still exists on PackageControl so when I push a tagged release it will eventually be picked up automatically.

You're free to continue using GS via PC if you like but the main reason I recommend against it is because last time I checked, it didn't support non-automatic updates for one package.

Ignoring the potential security issue of having unsandboxed code automatically pushed to your machine and executed in the background, the main reason I recommend not automatically updating GS (and any other package) is because it means that if I push an update that has a bug you could be in the middle of some important work and then suddenly the editor is broken or you lose your work.

**Comment by mholt** [comment]
Ohh. I understand now. (Sorry, all that wasn't really clear to me from the readme. Thank you for explaining!)

**Comment by Kiura** [comment]
Hello, I am still having issues on installing GoSublime

Here are the steps I followed:
1) `brew install go`
2) `git clone https://git.kuroku.io/GoSublime -b development` in Packages directory
3) cmd+., cmd+x

After that I expect to have code completion, autoimport, formatting. I have nothing...
After I uncomment `golang.GoFmt` line in margo.go I get code formating but thats it.
I believe if I uncomment golang.GoImports I will have autoimport as well, but these commands seem to override default ones.

Is there any stemps I am missing? If there is I would highly appreciate if some one shared a margo.go file or the steps I missed @dmitshur,  @DisposaBoy

**Comment by DisposaBoy** [comment]
@Kiura did you read all the comments in the file? fmt is not enabled by default because there's more than 1 choice; you'll have to choose between GoFmt and GoImports otherwise they just compete with each other.

Other than that, completion should work, but you need to make sure the packages are installed.

You can work-around that by using one of the reducers that install-on-save like `golang.GoInstallDiscardBinaries("-i")` or `golang.GoInstall("-i")` - again, be sure to read the comments to see what they do.

If that doesn't work, then please open a new issue with your `margo.go` file and check the console to see if there are any errors.

**Comment by Kiura** [comment]
@DisposaBoy, After I installed all packages I got completions working, now almost everything works (for some reason completions didn't work for stdlib either):
1. completions
2. formatting
3. go to definition

But imports are not working with GoFmt (not sure if they are supposed to), should I use go imports instead?
And thx for quick response :)

**Comment by DisposaBoy** [comment]
@Kiura Yes, use GoImports GoFmt only does the equivalent of the standard `gofmt` tool, so no automatic imports, automatic import grouping, etc.
